In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

np.random.seed(42)
n = 1000

data = {
    "CustomerID": np.arange(1, n+1),
    "Age": np.random.randint(18, 65, size=n),
    "Gender": np.random.choice(["Male", "Female"], size=n),
    "AnnualIncome": np.round(np.random.normal(100, 30, size=n), 2),
    "SpendingScore": np.random.randint(1, 101, size=n),
    "MembershipLevel": np.random.choice(["Silver", "Gold", "Platinum"], size=n, p=[0.5, 0.3, 0.2]),
    "City": np.random.choice(["Jakarta", "Bandung", "Surabaya", "Yogyakarta", "Medan"], size=n),
    "TimeOnApp": np.round(np.random.normal(2.5, 1.0, size=n), 2),
    "LastPurchaseDays": np.random.randint(0, 90, size=n),
    "Target": np.random.choice([0, 1], size=n, p=[0.6, 0.4])
}

df = pd.DataFrame(data)

print("Contoh data:")
print(df.head())

print("\nStatistik deskriptif:")
print(df.describe(include='all'))

print("\nDistribusi target:")
print(df['Target'].value_counts(normalize=True))

print("\nKorelasi antar variabel numerik:")
print(df.corr(numeric_only=True))

Contoh data:
   CustomerID  Age  Gender  AnnualIncome  SpendingScore MembershipLevel  \
0           1   56    Male         83.34             19          Silver
1           2   46  Female        156.43             37            Gold
2           3   32  Female         56.56             85          Silver
3           4   60  Female         34.04              8            Gold
4           5   25    Male        113.20             28          Silver

      City  TimeOnApp  LastPurchaseDays  Target
0  Bandung       4.05                77       0
1  Jakarta       4.91                71       0
2  Bandung       2.03                 8       0
3  Jakarta       2.07                34       1
4  Bandung       2.25                20       0

Statistik deskriptif:
         CustomerID          Age Gender  AnnualIncome  SpendingScore  \
count   1000.000000  1000.000000   1000   1000.000000    1000.000000
unique          NaN          NaN      2           NaN            NaN
top             NaN          NaN   Male           NaN            NaN
freq            NaN          NaN    526           NaN            NaN
mean     500.500000    40.986000    NaN    101.705460      50.838000
std      288.819436    13.497852    NaN     30.018484      28.750728
min        1.000000    18.000000    NaN     12.360000       1.000000
25%      250.750000    29.000000    NaN     81.542500      26.000000
50%      500.500000    42.000000    NaN    101.265000      51.000000
75%      750.250000    52.000000    NaN    121.595000      75.250000
max     1000.000000    64.000000    NaN    195.790000     100.000000

       MembershipLevel      City    TimeOnApp  LastPurchaseDays       Target
count             1000      1000  1000.000000       1000.000000  1000.000000
unique               3         5          NaN               NaN          NaN
top             Silver  Surabaya          NaN               NaN          NaN
freq               494       205          NaN               NaN          NaN
mean               NaN       NaN     2.503670         44.784000     0.426000
std                NaN       NaN     0.987759         26.105571     0.494741
min                NaN       NaN    -0.780000          0.000000     0.000000
25%                NaN       NaN     1.850000         22.000000     0.000000
50%                NaN       NaN     2.445000         44.000000     0.000000
75%                NaN       NaN     3.160000         69.000000     1.000000
max                NaN       NaN     5.270000         89.000000     1.000000

Distribusi target:
Target
0    0.574
1    0.426
Name: proportion, dtype: float64

Korelasi antar variabel numerik:
                  CustomerID       Age  AnnualIncome  SpendingScore  \
CustomerID          1.000000 -0.024857     -0.023234       0.036717
Age                -0.024857  1.000000     -0.016884      -0.029633
AnnualIncome       -0.023234 -0.016884      1.000000      -0.042837
SpendingScore       0.036717 -0.029633     -0.042837       1.000000
TimeOnApp          -0.014149  0.013493     -0.004611      -0.020595
LastPurchaseDays    0.019993 -0.017846      0.011492       0.013584
Target              0.024007  0.006140     -0.014054      -0.016537

                  TimeOnApp  LastPurchaseDays    Target
CustomerID        -0.014149          0.019993  0.024007
Age                0.013493         -0.017846  0.006140
AnnualIncome      -0.004611          0.011492 -0.014054
SpendingScore     -0.020595          0.013584 -0.016537
TimeOnApp          1.000000         -0.007105 -0.039274
LastPurchaseDays  -0.007105          1.000000 -0.008292
Target            -0.039274         -0.008292  1.000000